Do not install dependencies.
Instead, failfast if they aren't found, and suggest that the user
installs them manually instead.

diff --git a/build-from-tree b/build-from-tree
--- a/build-from-tree
+++ b/build-from-tree
@@ -7,6 +7,7 @@
 
 # TODO: Add parameter for other series. Right now it's xenial only.
 # TODO: Reuse buildd environment if found.
+# TODO: Export bzr tree for uat instead of cloning... we don't care here
 
 getopt --test > /dev/null
 if [[ $? -ne 4 ]]; then
@@ -38,14 +39,19 @@ while true; do
     esac
 done
 
-if [ $UID != 0 ] ; then
-    echo "You must run this script as root."
-    echo "It needs to install packages and modprobe overlay"
-    exit 1 
-fi
+DEPENDENCIES=(launchpad-buildd bzr python-ubuntutools)
+
+for dep in ${DEPENDENCIES[@]} ; do
+    if ! [[ $(dpkg -l | grep ^ii | grep $dep) != "" ]] ; then
+        echo "Please install the required dependencies for this script:"
+        echo "  sudo add-apt-repository -y -u ppa:launchpad/ppa"
+        echo "  sudo apt install -y ${DEPENDENCIES[@]}"
+        exit 1
+    fi
+done
 
 if [ $(lsb_release -s -c) == "bionic" ] ; then
-    echo "This currently doesn't work on bionic. Please run this on xenial."
+    echo "This currently doesn't work on bionic."
     exit 1
 fi
 
@@ -60,11 +66,6 @@ fi
 # The real script
 
 set -xe
-
-# TODO: Skip over adding PPA and installing if packages are already installed.
-# The launchpad PPA has launchpad-buildd and some of its dependencies.
-sudo add-apt-repository -y -u ppa:launchpad/ppa
-sudo apt install -y launchpad-buildd bzr python-ubuntutools
 
 # Load overlayfs kernel module for MAAS
 # XXX: Not 100% sure we want this since I'm not sure we will want to build MAAS
