Move image build into helper function
Also a little bit of cleanup

diff --git a/scripts/ubuntu-bartender/ubuntu-bartender b/scripts/ubuntu-bartender/ubuntu-bartender
--- a/scripts/ubuntu-bartender/ubuntu-bartender
+++ b/scripts/ubuntu-bartender/ubuntu-bartender
@@ -188,6 +188,63 @@ prepare_ingredients() {
 	)
 }
 
+build_images() {
+	local temp_dir
+	local bartender_name
+	local drink_name
+
+	temp_dir="$(mktemp --directory)"
+	bartender_name="$(petname)-ubuntu-bartender"
+	drink_name="${bartender_name/-bartender/-on-the-rocks.tar.gz}"
+
+	build-provider-assert-ready
+
+	cleanup() {
+		echo "Cleaning up..."
+		rm -rf "${temp_dir}"
+		build-provider-destroy "${bartender_name}"
+	}
+
+	if [[ "${SHOULD_CLEANUP}" = "YES" ]]; then
+		trap cleanup EXIT
+	fi
+
+	build-provider-create "${bartender_name}"
+
+	echo "Preparing ingredients..."
+	prepare_ingredients "${temp_dir}"
+	build-provider-upload "${bartender_name}" "${temp_dir}/ingredients.tar.gz" "ingredients.tar.gz"
+	build-provider-run "${bartender_name}" -- tar xf "ingredients.tar.gz"
+
+	echo "Mixing drink... (See progress in ${bartender_name}.log)"
+	cat > "${temp_dir}/mix-old-fashioned" <<- EOF
+		#!/bin/bash -x
+		sudo add-apt-repository -y -u ppa:launchpad/ppa
+		sleep 2
+		sudo apt-get -q update
+		sleep 2
+		sudo apt-get -q install -y \
+			launchpad-buildd \
+			python-ubuntutools \
+			python3-ubuntutools \
+			python3-launchpadlib \
+			bzr \
+			git
+		cd livecd-rootfs
+		sudo -E ../ubuntu-old-fashioned/old-fashioned-image-build \
+			${chroot_archive_flag[@]} \
+			${series_flag[@]} \
+			--no-cleanup \
+			${@}
+	EOF
+	build-provider-upload "${bartender_name}" "${temp_dir}/mix-old-fashioned" "mix-old-fashioned"
+	build-provider-run "${bartender_name}" -- bash mix-old-fashioned &>"${bartender_name}.log" </dev/null
+
+	echo "Pouring ${drink_name}..."
+	build-provider-run "${bartender_name}" -- tar czf "drink.tar.gz" "build.output"
+	build-provider-download "${bartender_name}" "drink.tar.gz" "${drink_name}"
+}
+
 assert_dependencies_installed
 
 apply_default_bartender_configuration
@@ -228,64 +285,19 @@ while [[ $# -gt 0 ]]; do
 	esac
 done
 
-if [ "$SHOW_HELP" = "YES" ]
-then
+if [[ "${SHOW_HELP}" = "YES" ]]; then
 	print_usage
 	exit 255
 fi
 
 load_build_provider_configuration
 
-build-provider-assert-ready
-
-if [ -z "$series_flag" ] && ! echo -- $@ | grep -q -- --series
-then
-	echo "error: the '--series' option is required by ubuntu-old-fashioned" >&2
+# The --series flag is required by ubuntu-old-fashioned for image builds,
+# so we check to make sure we have it before moving on:
+if [[ -z "${series_flag[*]}" ]] && ! echo -- "${@}" | grep -q -- --series; then
+	echo -e "\nerror: the '--series' option is required by ubuntu-old-fashioned\n" >&2
 	print_usage
 	exit 255
 fi
 
-temp_dir=$(mktemp --directory)
-bartender_name=$(petname)-ubuntu-bartender
-drink_name=${bartender_name/-bartender/-on-the-rocks.tar.gz}
-
-function cleanup {
-	echo "Cleaning up..."
-	rm -rf $temp_dir
-	build-provider-destroy $bartender_name
-}
-
-if [ "$SHOULD_CLEANUP" = "YES" ]
-then
-	trap cleanup EXIT
-fi
-
-build-provider-create $bartender_name
-
-(
-	echo "Preparing ingredients..."
-	prepare_ingredients "${temp_dir}"
-
-	cd $temp_dir
-
-	build-provider-upload $bartender_name ingredients.tar.gz ingredients.tar.gz
-	build-provider-run $bartender_name -- tar xf ingredients.tar.gz
-
-	cat > mix-old-fashioned <<- EOF
-		#!/bin/bash -x
-		sudo add-apt-repository -y -u ppa:launchpad/ppa
-		sudo apt-get -q update
-		sudo apt-get -q install -y launchpad-buildd bzr python-ubuntutools git python3-ubuntutools python3-launchpadlib
-		cd livecd-rootfs
-		sudo -E ../ubuntu-old-fashioned/old-fashioned-image-build --no-cleanup $chroot_archive_flag $series_flag $@
-	EOF
-	build-provider-upload $bartender_name mix-old-fashioned mix-old-fashioned
-)
-
-echo "Mixing drink..."
-echo "(See progress in $bartender_name.log)"
-build-provider-run $bartender_name -- bash mix-old-fashioned &>$bartender_name.log </dev/null
-
-echo "Pouring $drink_name..."
-build-provider-run $bartender_name -- tar czf drink.tar.gz build.output
-build-provider-download $bartender_name drink.tar.gz $drink_name
+build_images "${@}"
