Split multipass out as a build-provider.

diff --git a/scripts/ubuntu-bartender/ubuntu-bartender b/scripts/ubuntu-bartender/ubuntu-bartender
--- a/scripts/ubuntu-bartender/ubuntu-bartender
+++ b/scripts/ubuntu-bartender/ubuntu-bartender
@@ -28,13 +28,13 @@
 
 # The Ubuntu Bartender requires the following executables to be in the PATH:
 
-dependencies="multipass petname git"
+dependencies="petname git"
 
 # Which we verify before moving on:
 
 for dependency in $dependencies
 do
-  if ! which $dependency &>/dev/null
+  if ! command -v $dependency &>/dev/null
   then
     echo "error: $dependency was not found in PATH" >&2
     print-usage
@@ -56,11 +56,10 @@ UBUNTU_OLD_FASHIONED_BRANCH='master'
 LIVECD_ROOTFS_BRANCH='ubuntu/master'
 HOOK_EXTRAS_BRANCH=''
 
-# The Ubuntu Bartender utilizes a Multipass VM to build Ubuntu Images
-# that can be configured as well:
+# The Ubuntu Bartender utilizes a build-provider to create Ubuntu Images.
+# We use multipass by default:
 
-MULTIPASS_VM_DISK_SIZE='50G'
-MULTIPASS_VM_MEM_SIZE='8G'
+BUILD_PROVIDER=multipass
 
 # You shouldn't modify this script to change these default values.
 # Instead, put your personal configuration in a user config:
@@ -122,11 +121,9 @@ usage: $0 [<options>] -- --series <series> [<ubuntu-old-fashioned-options>]
     --hook-extras-branch <branch>           The branch of the extras-repo to use.
                                             Value: ${HOOK_EXTRAS_BRANCH:-None}
 
-    --multipass-vm-disk-size <size>         The disk size to use for the multipass vm.
-                                            Value: $MULTIPASS_VM_DISK_SIZE
-
-    --multipass-vm-mem-size <size>          The amount of ram to use for the multipass vm.
-                                            Value: $MULTIPASS_VM_MEM_SIZE
+    --build-provider <provider>             The provider used to build the image.
+                                            This can be either multipass or aws.
+                                            Value: $BUILD_PROVIDER
 
     --help                                  Print this help message.
 
@@ -164,12 +161,8 @@ do
       HOOK_EXTRAS_BRANCH="$2"
       shift
       ;;
-    --multipass-vm-disk-size)
-      MULTIPASS_VM_DISK_SIZE="$2"
-      shift
-      ;;
-    --multipass-vm-mem-size)
-      MULTIPASS_VM_MEM_SIZE="$2"
+    --build-provider)
+      BUILD_PROVIDER="$2"
       shift
       ;;
     --)
@@ -189,6 +182,20 @@ do
   shift
 done
 
+# Verify that the specified build provider is available and ready
+
+build_provider_config="$(dirname "$(readlink -f "$0")")/$BUILD_PROVIDER-provider"
+if [ ! -f "$build_provider_config" ]
+then
+  echo "error: invalid build provider specified: $BUILD_PROVIDER" >&2
+  print-usage
+  exit 255
+fi
+
+source "$build_provider_config"
+
+build-provider-assert-ready
+
 # The --series flag is required by ubuntu-old-fashioned for image builds,
 # so we check to make sure we have it before moving on:
 
@@ -201,7 +208,7 @@ fi
 
 ############ Where the Magic Happens ##########################################
 
-# Let's use multipass to build all the things!
+# Let's build all the things!
 
 temp_dir=$(mktemp --directory)
 bartender_name=$(petname)-ubuntu-bartender
@@ -210,14 +217,11 @@ drink_name=${bartender_name/-bartender/-on-the-rocks.tar.gz}
 function cleanup {
   echo "Cleaning up..."
   rm -rf $temp_dir
-  multipass delete -p $bartender_name
+  build-provider-destroy $bartender_name
 }
 trap cleanup EXIT
 
-multipass launch --disk $MULTIPASS_VM_DISK_SIZE \
-                 --mem $MULTIPASS_VM_MEM_SIZE \
-                 --name $bartender_name \
-                 daily:x
+build-provider-create $bartender_name
 
 (
   cd $temp_dir
@@ -245,16 +249,15 @@ cd livecd-rootfs
 sudo -E ../ubuntu-old-fashioned/old-fashioned-image-build --no-cleanup $series_flag $@
 EOF
 
-  tar czf ingredients.tar.gz *
-  multipass transfer ingredients.tar.gz $bartender_name:
+  tar czf ingredients.tar.gz ./*
+  build-provider-upload $bartender_name ingredients.tar.gz ingredients.tar.gz
 )
 
-echo "Mixing drink. This may take a while..."
+echo "Mixing drink..."
 echo "(See progress in $bartender_name.log)"
-multipass exec $bartender_name -- tar xf ingredients.tar.gz
-multipass exec $bartender_name -- bash mix-old-fashioned &>$bartender_name.log </dev/null
-multipass exec $bartender_name -- tar czf drink.tar.gz build.output
+build-provider-run $bartender_name -- tar xf ingredients.tar.gz
+build-provider-run $bartender_name -- bash mix-old-fashioned &>$bartender_name.log </dev/null
+build-provider-run $bartender_name -- tar czf drink.tar.gz build.output
 
 echo "Pouring $drink_name..."
-multipass transfer $bartender_name:drink.tar.gz $drink_name
-
+build-provider-download $bartender_name drink.tar.gz $drink_name
